internalParams:
  uki: true
  # TODO: Remove this internal parameter once UKI & encryption tests are fixed.
  # https://dev.azure.com/mariner-org/polar/_workitems/edit/13344/.
  overridePcrlockEncryption: true
image:
  url: http://NETLAUNCH_HOST_ADDRESS/files/usrverity.cosi
  sha384: ignored
storage:
  disks:
    - id: os
      device: /dev/disk/by-path/pci-0000:00:1f.2-ata-2
      partitionTableType: gpt
      partitions:
        - id: esp
          type: esp
          size: 1G
        - id: boot-a
          type: xbootldr
          size: 200M
        - id: boot-b
          type: xbootldr
          size: 200M
        - id: root-a-1
          size: 2G
        - id: root-b-1
          size: 2G
        - id: usr-data-a-1
          size: 2G
        - id: usr-data-b-1
          size: 2G
        - id: usr-hash-a-1
          size: 256M
        - id: usr-hash-b-1
          size: 256M
        - id: web-a-e-1
          size: 1G
        - id: web-b-e-1
          size: 1G
        - id: trident
          size: 500M
    - id: disk2
      device: /dev/disk/by-path/pci-0000:00:1f.2-ata-3
      partitionTableType: gpt
      partitions:
        - id: root-a-2
          size: 2G
        - id: root-b-2
          size: 2G
        - id: usr-data-a-2
          size: 2G
        - id: usr-data-b-2
          size: 2G
        - id: usr-hash-a-2
          size: 256M
        - id: usr-hash-b-2
          size: 256M
        - id: web-a-e-2
          size: 1G
        - id: web-b-e-2
          size: 1G
  encryption:
    volumes:
      - id: web-a
        deviceName: web-a
        deviceId: web-a-e
      - id: web-b
        deviceName: web-b
        deviceId: web-b-e
    pcrs:
      - boot-loader-code # 4
      # TODO: Once UKI MOS is built and pcrlock policy can include PCR 7,
      # un-comment. Related ADO task:
      # https://dev.azure.com/mariner-org/polar/_workitems/edit/14286/.
      #- secure-boot-policy # 7
      - kernel-boot # 11
  raid:
    software:
      - id: root-a
        name: root-a
        level: raid1
        devices:
          - root-a-1
          - root-a-2
      - id: root-b
        name: root-b
        level: raid1
        devices:
          - root-b-1
          - root-b-2

      - id: usr-data-a
        name: usr-data-a
        level: raid1
        devices:
          - usr-data-a-1
          - usr-data-a-2
      - id: usr-data-b
        name: usr-data-b
        level: raid1
        devices:
          - usr-data-b-1
          - usr-data-b-2
      - id: usr-hash-a
        name: usr-hash-a
        level: raid1
        devices:
          - usr-hash-a-1
          - usr-hash-a-2
      - id: usr-hash-b
        name: usr-hash-b
        level: raid1
        devices:
          - usr-hash-b-1
          - usr-hash-b-2

      - id: web-a-e
        name: web-a-e
        level: raid1
        devices:
          - web-a-e-1
          - web-a-e-2
      - id: web-b-e
        name: web-b-e
        level: raid1
        devices:
          - web-b-e-1
          - web-b-e-2
  abUpdate:
    volumePairs:
      - id: boot
        volumeAId: boot-a
        volumeBId: boot-b
      - id: root
        volumeAId: root-a
        volumeBId: root-b
      - id: usr-data
        volumeAId: usr-data-a
        volumeBId: usr-data-b
      - id: usr-hash
        volumeAId: usr-hash-a
        volumeBId: usr-hash-b
      - id: web
        volumeAId: web-a
        volumeBId: web-b
  verity:
    - id: usr
      name: usr
      dataDeviceId: usr-data
      hashDeviceId: usr-hash
  filesystems:
    - deviceId: esp
      mountPoint:
        path: /boot/efi
        options: umask=0077
    - deviceId: boot
      mountPoint: /boot
    - deviceId: root
      mountPoint: /
    - deviceId: usr
      mountPoint:
        path: /usr
        options: defaults,ro
    - deviceId: web
      source: new
      mountPoint: /web
    - deviceId: trident
      source: new
      mountPoint: /var/lib/trident
os:
  selinux:
    mode: enforcing
  netplan:
    version: 2
    ethernets:
      vmeths:
        match:
          name: enp*
        dhcp4: true
  users:
    - name: testing-user
      sshPublicKeys: []
      secondaryGroups:
        - wheel
      sshMode: key-only
