bareMetal:
  host:
    daily:
      - base
      - combined
      - encrypted-partition
      - split
      - usr-verity
    validation:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - memory-constraint-combined
      - misc
      - raid-big
      - raid-mirrored
      - raid-resync-small
      - rerun
      - root-verity
      - simple
      - split
      - usr-verity
      - usr-verity-raid
    weekly:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - memory-constraint-combined
      - misc
      - raid-big
      - raid-mirrored
      - raid-resync-small
      - rerun
      - root-verity
      - simple
      - split
      - usr-verity
      - usr-verity-raid
  container:
    daily:
      - base
      - combined
      - encrypted-swap
      - misc
      - raid-small
      - rerun
      - root-verity
    validation:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - misc
      - raid-mirrored
      - raid-resync-small
      - raid-small
      - rerun
      - root-verity
      - simple
      - usr-verity
      - usr-verity-raid
    weekly:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - misc
      - raid-mirrored
      - raid-resync-small
      - raid-small
      - rerun
      - root-verity
      - simple
      - usr-verity
      - usr-verity-raid
virtualMachine:
  host:
    daily:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - memory-constraint-combined
      - misc
      - raid-mirrored
      - raid-resync-small
      - raid-small
      - rerun
      - root-verity
      - simple
      - split
      - usr-verity
      - usr-verity-raid
    post_merge:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - memory-constraint-combined
      - misc
      - raid-mirrored
      - raid-resync-small
      - raid-small
      - rerun
      - root-verity
      - simple
      - split
      - usr-verity
      - usr-verity-raid
    pullrequest:
      - base
      - combined
      - misc
      - raid-mirrored
      - raid-resync-small
      - rerun
      - root-verity
      - simple
      - split
      - usr-verity
      - usr-verity-raid
    validation:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - memory-constraint-combined
      - misc
      - raid-mirrored
      - raid-resync-small
      - raid-small
      - rerun
      - root-verity
      - simple
      - split
      - usr-verity
      - usr-verity-raid
    weekly:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - memory-constraint-combined
      - raid-mirrored
      - raid-resync-small
      - raid-small
      - rerun
      - root-verity
      - simple
      - split
      - usr-verity
      - usr-verity-raid
  container:
    daily:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - misc
      - raid-mirrored
      - raid-resync-small
      - raid-small
      - rerun
      - root-verity
      - simple
      - usr-verity
      - usr-verity-raid
    post_merge:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - misc
      - raid-mirrored
      - raid-resync-small
      - raid-small
      - rerun
      - root-verity
      - simple
      - usr-verity
      - usr-verity-raid
    pullrequest:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - misc
      - raid-mirrored
      - raid-resync-small
      - rerun
      - simple
      - usr-verity
      - usr-verity-raid
    validation:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - misc
      - raid-mirrored
      - raid-resync-small
      - raid-small
      - rerun
      - root-verity
      - simple
      - usr-verity
      - usr-verity-raid
    weekly:
      - base
      - combined
      - encrypted-partition
      - encrypted-raid
      - encrypted-swap
      - raid-mirrored
      - raid-resync-small
      - raid-small
      - rerun
      - root-verity
      - simple
      - usr-verity
      - usr-verity-raid
