[net]
git-fetch-with-cli = true

[registries]
BMP_PublicPackages = { index = "sparse+https://pkgs.dev.azure.com/mariner-org/ECF/_packaging/BMP_PublicPackages/Cargo/index/" }
PolarCoreArtifacts = { index = "sparse+https://pkgs.dev.azure.com/mariner-org/polar/_packaging/PolarCoreArtifacts/Cargo/index/" }
TridentDev = { index = "sparse+https://pkgs.dev.azure.com/mariner-org/ECF/_packaging/TridentDev/Cargo/index/" }

[source.crates-io]
replace-with = "BMP_PublicPackages"
