internalParams:
  uki: true
image:
  url: http://NETLAUNCH_HOST_ADDRESS/files/usrverity.cosi
  sha384: ignored
trident:
  selfUpgrade: false
storage:
  disks:
    - id: os
      device: /dev/disk/by-path/pci-0000:00:1f.2-ata-2
      partitionTableType: gpt
      partitions:
        - id: esp
          size: 1G
          type: esp
        - id: boot-a
          size: 250M
        - id: boot-b
          size: 250M
        - id: root-a
          size: 5G
          type: root
        - id: root-b
          size: 5G
          type: root
        - id: usr-data-a
          size: 5G
          type: usr
        - id: usr-data-b
          size: 5G
          type: usr
        - id: usr-hash-a
          size: 1G
          type: usr-verity
        - id: usr-hash-b
          size: 1G
          type: usr-verity
        - id: trident
          type: linux-generic
          size: 1G
    - id: disk2
      device: /dev/disk/by-path/pci-0000:00:1f.2-ata-3
      partitionTableType: gpt
      partitions: []
  abUpdate:
    volumePairs:
      - id: boot
        volumeAId: boot-a
        volumeBId: boot-b
      - id: root
        volumeAId: root-a
        volumeBId: root-b
      - id: usr-data
        volumeAId: usr-data-a
        volumeBId: usr-data-b
      - id: usr-hash
        volumeAId: usr-hash-a
        volumeBId: usr-hash-b
  verity:
    - id: usr
      name: usr
      dataDeviceId: usr-data
      hashDeviceId: usr-hash
  filesystems:
    - deviceId: esp
      mountPoint:
        path: /boot/efi
        options: umask=0077
    - deviceId: boot
      mountPoint: /boot
    - deviceId: root
      mountPoint: /
    - deviceId: usr
      mountPoint:
        path: /usr
        options: ro
    - deviceId: trident
      source: new
      mountPoint: /var/lib/trident
os:
  selinux:
    mode: enforcing
  netplan:
    version: 2
    ethernets:
      vmeths:
        match:
          name: enp*
        dhcp4: true
  users:
    - name: testing-user
      sshPublicKeys: []
      secondaryGroups:
        - wheel
      sshMode: key-only
